services:
  api:
    build:
      dockerfile: api.Dockerfile
    working_dir: /app
    volumes:
      - ./api:/app/src
    command: CompileDaemon -directory=/app/src -build="go build -o /app/api" -command=/app/api
    ports:
      - "8320:8320"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=docrepo
      - DB_SSLMODE=disable
      - PORT=8320
    depends_on:
      - db

  frontend:
    image: nginx:1.27.4-alpine
    ports:
      - "8321:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - api

  db:
    image: postgres:17.4-alpine
    ports:
      - "8322:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=docrepo
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
